export const addRoomFormElements = [
     {
       label: "Room Name",
       name: "name",
       componentType: "input",
       type: "text",
       placeholder: "Enter room title",
     },
     {
       label: "Price per hour (in USD)",
       name: "price",
       componentType: "input",
       type: "number",
       placeholder: "Enter price per hour",
     },
     {
       label: "Length (in feet)",
       name: "lengthInFeet",
       componentType: "input",
       type: "number",
       placeholder: "Enter room length in feet",
     },
     {
       label: "Width (in feet)",
       name: "widthInFeet",
       componentType: "input",
       type: "number",
       placeholder: "Enter room width in feet",
     },
     {
       label: "Address",
       name: "address",
       componentType: "input",
       type: "text",
       placeholder: "Enter room address",
     },
     {
       label: "City",
       name: "city",
       componentType: "input",
       type: "text",
       placeholder: "Enter city",
     },
     {
       label: "State",
       name: "state",
       componentType: "input",
       type: "text",
       placeholder: "Enter state",
     },
     {
       label: "Pin Code",
       name: "pin",
       componentType: "input",
       type: "number",
       placeholder: "Enter pin code",
     },
     {
       label: "Description",
       name: "description",
       componentType: "textarea",
       placeholder: "Enter room description (optional)",
     },
   ];
   